### ISSUE TITLE
[Question] GetUnderlyingElementType exception thrown

### ISSUE THREAD

**Issue by DanielGlos** [BlaiseD/LogicBuilder.DataComponents#19]
Hi,

I'm facing a problem with mentioned method.

       public static Type GetUnderlyingElementType(this Type type)
        {
            TypeInfo tInfo = type.GetTypeInfo();
            if (tInfo.IsArray)
                return tInfo.GetElementType();

            Type[] genericArguments;
            if (!tInfo.IsGenericType || (genericArguments = tInfo.GetGenericArguments()).Length != 1)
                throw new ArgumentException("type");

            return genericArguments[0];
        }

Inside the method you are throwing ArgumentException("type") after checking if number of generic arguments is not equal to 1 so when Dictionary<string, object> is passed in as a type it fails. Could you please provide some info why this check is necessary. I have tried removing this check and it seems to work fine.

**Comment by BlaiseD** [comment]
It will work - given that it's an exception.  Only a negative test can fail.

It is designed for an `IEnumerable<T>`  where T = some entity -  not an underlying key-value pair (`IEnumerable<KeyValuePair<string, object>> o = new Dictionary<string, object>();`).

How are you trying to use it?
